/*
 * Copyright 2021 The BF Project
 *
 * The BF Project licenses this file to you under the Apache License,
 * version 2.0 (the "License"); you may not use this file except in compliance
 * with the License. You may obtain a copy of the License at:
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 */
package org.bf.classfile.op;

public class InstructionSet {
    private final static OpBuilder[] set = {
            b(0,"nop","Do nothing","e"),
            b(1,"aconst_null","Push null","e"),
            b(2,"iconst_m1","Push int constant","e"),
            b(3,"iconst_0","Push int constant","e"),
            b(4,"iconst_1","Push int constant","e"),
            b(5,"iconst_2","Push int constant","e"),
            b(6,"iconst_3","Push int constant","e"),
            b(7,"iconst_4","Push int constant","e"),
            b(8,"iconst_5","Push int constant","e"),
            b(9,"lconst_0","Push long constant","e"),
            b(10,"lconst_1","Push long constant","e"),
            b(11,"fconst_0","Push float","e"),
            b(12,"fconst_1","Push float","e"),
            b(13,"fconst_2","Push float","e"),
            b(14,"dconst_0","Push double","e"),
            b(15,"dconst_1","Push double","e"),
            b(16,"bipush","Push byte","b_si"),
            b(17,"sipush","Push short","2b_si"),
            b(18,"ldc","Push item from run-time constant pool","b"),
            b(19,"ldc_w","Push item from run-time constant pool (wide index)","2b"),
            b(20,"ldc2_w","Push long or double from run-time constant pool (wide index)","2b"),
            b(21,"iload","Load int from local variable","b"),
            b(22,"lload","Load long from local variable","b"),
            b(23,"fload","Load float from local variable","b"),
            b(24,"dload","Load double from local variable","b"),
            b(25,"aload","Load reference from local variable","b"),
            b(26,"iload_0","Load int from local variable","e"),
            b(27,"iload_1","Load int from local variable","e"),
            b(28,"iload_2","Load int from local variable","e"),
            b(29,"iload_3","Load int from local variable","e"),
            b(30,"lload_0","Load long from local variable","e"),
            b(31,"lload_1","Load long from local variable","e"),
            b(32,"lload_2","Load long from local variable","e"),
            b(33,"lload_3","Load long from local variable","e"),
            b(34,"fload_0","Load float from local variable","e"),
            b(35,"fload_1","Load float from local variable","e"),
            b(36,"fload_2","Load float from local variable","e"),
            b(37,"fload_3","Load float from local variable","e"),
            b(38,"dload_0","Load double from local variable","e"),
            b(39,"dload_1","Load double from local variable","e"),
            b(40,"dload_2","Load double from local variable","e"),
            b(41,"dload_3","Load double from local variable","e"),
            b(42,"aload_0","Load reference from local variable","e"),
            b(43,"aload_1","Load reference from local variable","e"),
            b(44,"aload_2","Load reference from local variable","e"),
            b(45,"aload_3","Load reference from local variable","e"),
            b(46,"iaload","Load int from array","e"),
            b(47,"laload","Load long from array","e"),
            b(48,"faload","Load float from array","e"),
            b(49,"daload","Load double from array","e"),
            b(50,"aaload","Load reference from array","e"),
            b(51,"baload","Load byte or boolean from array","e"),
            b(52,"caload","Load char from array","e"),
            b(53,"saload","Load short from array","e"),
            b(54,"istore","Store int into local variable","b"),
            b(55,"lstore","Store long into local variable","b"),
            b(56,"fstore","Store float into local variable","b"),
            b(57,"dstore","Store double into local variable","b"),
            b(58,"astore","Store reference into local variable","b"),
            b(59,"istore_0","Store int into local variable","e"),
            b(60,"istore_1","Store int into local variable","e"),
            b(61,"istore_2","Store int into local variable","e"),
            b(62,"istore_3","Store int into local variable","e"),
            b(63,"lstore_0","Store long into local variable","e"),
            b(64,"lstore_1","Store long into local variable","e"),
            b(65,"lstore_2","Store long into local variable","e"),
            b(66,"lstore_3","Store long into local variable","e"),
            b(67,"fstore_0","Store float into local variable","e"),
            b(68,"fstore_1","Store float into local variable","e"),
            b(69,"fstore_2","Store float into local variable","e"),
            b(70,"fstore_3","Store float into local variable","e"),
            b(71,"dstore_0","Store double into local variable","e"),
            b(72,"dstore_1","Store double into local variable","e"),
            b(73,"dstore_2","Store double into local variable","e"),
            b(74,"dstore_3","Store double into local variable","e"),
            b(75,"astore_0","Store reference into local variable","e"),
            b(76,"astore_1","Store reference into local variable","e"),
            b(77,"astore_2","Store reference into local variable","e"),
            b(78,"astore_3","Store reference into local variable","e"),
            b(79,"iastore","Store into int array","e"),
            b(80,"lastore","Store into long array","e"),
            b(81,"fastore","Store into float array","e"),
            b(82,"dastore","Store into dobule array","e"),
            b(83,"aastore","Store into reference array","e"),
            b(84,"bastore","Store into byte or boolean array","e"),
            b(85,"castore","Store into char array","e"),
            b(86,"sastore","Store into short array","e"),
            b(87,"pop","Pop the top operand stack value","e"),
            b(88,"pop2","Pop the top one or two operand stack values","e"),
            b(89,"dup","Duplicate the top operand stack value","e"),
            b(90,"dup_x1","Duplicate the top operand stack value and insert two values down","e"),
            b(91,"dup_x2","Duplicate the top operand stack value and insert two or three values down","e"),
            b(92,"dup2","Duplicate the top one or two operand stack values","e"),
            b(93,"dup2_x1","Duplicate the top one or two operand stack values and insert two or three values down","e"),
            b(94,"dup2_x2","Duplicate the top one or two operand stack values and insert two three or four values down","e"),
            b(95,"swap","Swap the top two operand stack values","e"),
            b(96,"iadd","Add int","e"),
            b(97,"ladd","Add long","e"),
            b(98,"fadd","Add float","e"),
            b(99,"dadd","Add double","e"),
            b(100,"isub","Subtract int","e"),
            b(101,"lsub","Subtract long","e"),
            b(102,"fsub","Subtract float","e"),
            b(103,"dsub","Subtract double","e"),
            b(104,"imul","Multiply int","e"),
            b(105,"lmul","Multiply long","e"),
            b(106,"fmul","Multiply float","e"),
            b(107,"dmul","Multiply double","e"),
            b(108,"idiv","Divide int","e"),
            b(109,"ldiv","Divide long","e"),
            b(110,"fdiv","Divide float","e"),
            b(111,"ddiv","Divide double","e"),
            b(112,"irem","Remainder int","e"),
            b(113,"lrem","Remainder long","e"),
            b(114,"frem","Remainder float","e"),
            b(115,"drem","Remainder double","e"),
            b(116,"ineg","Negate int","e"),
            b(117,"lneg","Negate long","e"),
            b(118,"fneg","Negate float","e"),
            b(119,"dneg","Negate double","e"),
            b(120,"ishl","Shift left int","e"),
            b(121,"lshl","Shift left long","e"),
            b(122,"ishr","Arithmetic shift right int","e"),
            b(123,"lshr","Arithmetic shift right long","e"),
            b(124,"iushr","Logical shift right int","e"),
            b(125,"lushr","Logical shift right long","e"),
            b(126,"iand","Boolean AND int","e"),
            b(127,"land","Boolean AND long","e"),
            b(128,"ior","Boolean OR int","e"),
            b(129,"lor","Boolean OR long","e"),
            b(130,"ixor","Boolean XOR int","e"),
            b(131,"lxor","Boolean XOR long","e"),
            b(132,"iinc","Increment local variable by constant","b_sb"),
            b(133,"i2l","Convert int to long","e"),
            b(134,"i2f","Convert int to float","e"),
            b(135,"i2d","Convert int to double","e"),
            b(136,"l2i","Convert long to int","e"),
            b(137,"l2f","Convert long to float","e"),
            b(138,"l2d","Convert long to double","e"),
            b(139,"unused139","unused opcode", "u"),
            b(140,"f2l","Convert float to long","e"),
            b(141,"f2d","Convert float to double","e"),
            b(142,"d2i","Convert double to int","e"),
            b(143,"d2l","Convert double to long","e"),
            b(144,"d2f","Convert double to float","e"),
            b(145,"i2b","Convert int to byte","e"),
            b(146,"i2c","Convert int to char","e"),
            b(147,"i2s","Convert int to short","e"),
            b(148,"lcmp","Compare long","e"),
            b(149,"fcmpl","Compare float","e"),
            b(150,"fcmpg","Compare float","e"),
            b(151,"dcmpl","Compare double","e"),
            b(152,"dcmpg","Compare double","e"),
            b(153,"ifeq","Branch if int comparison with zero succeeds","2b_si"),
            b(154,"ifne","Branch if int comparison with zero succeeds","2b_si"),
            b(155,"iflt","Branch if int comparison with zero succeeds","2b_si"),
            b(156,"ifge","Branch if int comparison with zero succeeds","2b_si"),
            b(157,"ifgt","Branch if int comparison with zero succeeds","2b_si"),
            b(158,"ifle","Branch if int comparison with zero succeeds","2b_si"),
            b(159,"if_icmpeq","Branch if int comparison succeeds","2b_si"),
            b(160,"if_icmpne","Branch if int comparison succeeds","2b_si"),
            b(161,"if_icmplt","Branch if int comparison succeeds","2b_si"),
            b(162,"if_icmpge","Branch if int comparison succeeds","2b_si"),
            b(163,"if_icmpgt","Branch if int comparison succeeds","2b_si"),
            b(164,"if_icmple","Branch if int comparison succeeds","2b_si"),
            b(165,"if_acmpeq","Branch if reference comparison succeeds","2b_si"),
            b(166,"if_acmpne","Branch if reference comparison succeeds","2b_si"),
            b(167,"goto","Branch always","2b_si"),
            b(168,"jsr","Jump subroutine","2b_si"),
            b(169,"ret","Return from subroutine","b"),
            b(170,"tableswitch","Access jump table by index and jump","ts"),
            b(171,"lookupswitch","Access jump table by key match and jump","ls"),
            b(172,"ireturn","Return int from method","e"),
            b(173,"lreturn","Return long from method","e"),
            b(174,"freturn","Return float from method","e"),
            b(175,"dreturn","Return double from method","e"),
            b(176,"areturn","Return reference from method","e"),
            b(177,"return","Return void from method","e"),
            b(178,"getstatic","Get static field from class","2b"),
            b(179,"putstatic","Set static field in class","2b"),
            b(180,"getfield","Fetch field from object","2b"),
            b(181,"putfield","Set field in object","2b"),
            b(182,"invokevirtual","Invoke instance method; dispatch based on class","2b"),
            b(183,"invokespecial","Invoke instance method; special handling for superclass、private、 and instance initialization method invocations","2b"),
            b(184,"invokestatic","Invoke a class (static) method","2b"),
            b(185,"invokeinterface","Invoke interface method","ivi"),
            b(186,"invokedynamic","Invoke dynamic method","ivd"),
            b(187,"new","Create new object","2b"),
            b(188,"newarray","Create new array","b"),
            b(189,"anewarray","Create new array of reference","2b"),
            b(190,"arraylength","Get length of array","e"),
            b(191,"athrow","Throw exception or error","e"),
            b(192,"checkcast","Check whether object is of given type","2b"),
            b(193,"instanceof","Determine if object is of given type","2b"),
            b(194,"monitorenter","Enter monitor for object","e"),
            b(195,"monitorexit","Exit monitor for object","e"),
            b(196,"wide","Extend local variable index by additional bytes","wide"),
            b(197,"multianewarray","Create new multidimensional array","multi"),
            b(198,"ifnull","Branch if reference is null","2b_si"),
            b(199,"ifnonnull","Branch if reference not null","2b_si"),
            b(200,"goto_w","Branch always (wide index)","4b_si"),
            b(201,"jsr_w","Jump subroutine (wide index)","4b_si"),
            b(202,"breakpoint","breakpoint reserved","r"),
            b(203,"unused203","unused opcode", "u"),
            b(204,"unused204","unused opcode", "u"),
            b(205,"unused205","unused opcode", "u"),
            b(206,"unused206","unused opcode", "u"),
            b(207,"unused207","unused opcode", "u"),
            b(208,"unused208","unused opcode", "u"),
            b(209,"unused209","unused opcode", "u"),
            b(210,"unused210","unused opcode", "u"),
            b(211,"unused211","unused opcode", "u"),
            b(212,"unused212","unused opcode", "u"),
            b(213,"unused213","unused opcode", "u"),
            b(214,"unused214","unused opcode", "u"),
            b(215,"unused215","unused opcode", "u"),
            b(216,"unused216","unused opcode", "u"),
            b(217,"unused217","unused opcode", "u"),
            b(218,"unused218","unused opcode", "u"),
            b(219,"unused219","unused opcode", "u"),
            b(220,"unused220","unused opcode", "u"),
            b(221,"unused221","unused opcode", "u"),
            b(222,"unused222","unused opcode", "u"),
            b(223,"unused223","unused opcode", "u"),
            b(224,"unused224","unused opcode", "u"),
            b(225,"unused225","unused opcode", "u"),
            b(226,"unused226","unused opcode", "u"),
            b(227,"unused227","unused opcode", "u"),
            b(228,"unused228","unused opcode", "u"),
            b(229,"unused229","unused opcode", "u"),
            b(230,"unused230","unused opcode", "u"),
            b(231,"unused231","unused opcode", "u"),
            b(232,"unused232","unused opcode", "u"),
            b(233,"unused233","unused opcode", "u"),
            b(234,"unused234","unused opcode", "u"),
            b(235,"unused235","unused opcode", "u"),
            b(236,"unused236","unused opcode", "u"),
            b(237,"unused237","unused opcode", "u"),
            b(238,"unused238","unused opcode", "u"),
            b(239,"unused239","unused opcode", "u"),
            b(240,"unused240","unused opcode", "u"),
            b(241,"unused241","unused opcode", "u"),
            b(242,"unused242","unused opcode", "u"),
            b(243,"unused243","unused opcode", "u"),
            b(244,"unused244","unused opcode", "u"),
            b(245,"unused245","unused opcode", "u"),
            b(246,"unused246","unused opcode", "u"),
            b(247,"unused247","unused opcode", "u"),
            b(248,"unused248","unused opcode", "u"),
            b(249,"unused249","unused opcode", "u"),
            b(250,"unused250","unused opcode", "u"),
            b(251,"unused251","unused opcode", "u"),
            b(252,"unused252","unused opcode", "u"),
            b(253,"unused253","unused opcode", "u"),
            b(254,"impdep1","back doors or traps reserved","r"),
            b(255,"impdep2","back doors or traps reserved","r")
    };

    private static OpBuilder b(int opCode, String name, String desc, String type) {
        return new OpBuilder(new OpInfo(opCode, name, desc, type));
    }
    public final static Instruction getInstruction(int n) {
        return set[n].build();
    }
}
